export const products = [
  { id: 1, name: "Fresh Vegetables", price: 5, image: "/colorful-vegetable-basket.png" },
  { id: 2, name: "Organic Fruits", price: 8, image: "/organic-fruits.png" },
  { id: 3, name: "Olive Oil", price: 15, image: "/olive-oil.png" },
  { id: 4, name: "Locally-produced Wine", price: 25, image: "/local-red-wine.png" },
  { id: 5, name: "Honey & Beeswax", price: 12, image: "/golden-honey-jar.png" },
  { id: 6, name: "Artisanal Bread", price: 7, image: "/artisanal-bread.png" },
  { id: 7, name: "Handcrafted Pottery", price: 40, image: "/handcrafted-pottery.png" },
  { id: 8, name: "Dairy Products", price: 10, image: "/dairy-products.png" },
  { id: 9, name: "Preserves and Jams", price: 9, image: "/preserves-jams.png" },
  { id: 10, name: "Fresh Eggs", price: 4, image: "/fresh-eggs.png" },
  { id: 11, name: "Handmade Soaps", price: 8, image: "/handmade-soaps.png" },
  { id: 12, name: "Woven Textiles", price: 55, image: "/woven-textiles.png" },
  { id: 13, name: "Herbs and Spices", price: 3, image: "/herbs-spices.png" },
  { id: 14, name: "Nuts and Dried Fruits", price: 11, image: "/nuts-dried-fruits.png" },
  { id: 15, name: "Wooden Homeware", price: 60, image: "/wooden-homeware.png" },
  { id: 16, name: "Plants and Seedlings", price: 6, image: "/plants-seedlings.png" },
  { id: 17, name: "Local Artwork", price: 75, image: "/local-artwork.png" },
  { id: 18, name: "Homemade Pastries", price: 6, image: "/homemade-pastries.png" },
  { id: 19, name: "Pickled Vegetables", price: 7, image: "/pickled-vegetables.png" },
  { id: 20, name: "Natural Juices", price: 5, image: "/natural-juices.png" },
]
