export const products = [
  { id: 1, name: "Fresh Vegetables", price: 5, image: "/colorful-vegetable-basket.png" },
  { id: 2, name: "Organic Fruits", price: 8, image: "/placeholder-jmbz5.png" },
  { id: 3, name: "Olive Oil", price: 15, image: "/placeholder-uujfh.png" },
  { id: 4, name: "Locally-produced Wine", price: 25, image: "/local-red-wine.png" },
  { id: 5, name: "Honey & Beeswax", price: 12, image: "/golden-honey-jar.png" },
  { id: 6, name: "Artisanal Bread", price: 7, image: "/placeholder.svg?width=400&height=300" },
  { id: 7, name: "Handcrafted Pottery", price: 40, image: "/placeholder.svg?width=400&height=300" },
  { id: 8, name: "Dairy Products", price: 10, image: "/placeholder.svg?width=400&height=300" },
  { id: 9, name: "Preserves and Jams", price: 9, image: "/placeholder.svg?width=400&height=300" },
  { id: 10, name: "Fresh Eggs", price: 4, image: "/placeholder.svg?width=400&height=300" },
  { id: 11, name: "Handmade Soaps", price: 8, image: "/placeholder.svg?width=400&height=300" },
  { id: 12, name: "Woven Textiles", price: 55, image: "/placeholder.svg?width=400&height=300" },
  { id: 13, name: "Herbs and Spices", price: 3, image: "/placeholder.svg?width=400&height=300" },
  { id: 14, name: "Nuts and Dried Fruits", price: 11, image: "/placeholder.svg?width=400&height=300" },
  { id: 15, name: "Wooden Homeware", price: 60, image: "/placeholder.svg?width=400&height=300" },
  { id: 16, name: "Plants and Seedlings", price: 6, image: "/placeholder.svg?width=400&height=300" },
  { id: 17, name: "Local Artwork", price: 75, image: "/placeholder.svg?width=400&height=300" },
  { id: 18, name: "Homemade Pastries", price: 6, image: "/placeholder.svg?width=400&height=300" },
  { id: 19, name: "Pickled Vegetables", price: 7, image: "/placeholder.svg?width=400&height=300" },
  { id: 20, name: "Natural Juices", price: 5, image: "/placeholder.svg?width=400&height=300" },
]
